---
- include: consul.yml

- include: client.yml
  when: not consul_server

- name: add consul ui config
  copy: src=http_bind.json dest=/etc/consul.d/bind.json mode=0644
  notify: "restart consul"
  when: consul_server
