---
- name: install epel
  yum: name=epel-release state=installed

- name: install dependencies
  yum: name={{ item }} state=installed
  with_items:
    - nginx
    - libselinux-python

- name: write our nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: write our site config
  template: src=default-site.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: create template direcotry
  file: path=/etc/consul-template/templates state=directory

- name: deploy website content
  template: src=nginx.ctmpl.j2 dest=/etc/consul-template/templates/nginx.ctmpl

- name: register nginx service with curl check
  consul:
    service_name: nginx
    service_port: 80
    script: "curl http://localhost"
    interval: 60s
    tags:
      - webservers
